# Generated by Django 4.0.5 on 2022-06-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_in_stock',
            field=models.IntegerField(default=1),
        ),
    ]
